### ISSUE TITLE
Add a setting to disable the emoji alerts

### ISSUE THREAD

**Issue by leifmetcalf** [kevin49999/Go-iOS#18]
I have some beginner friends, and it’d be nice if they could find atari without the alerts.

If you take donations I’ll put a $50 bounty on this?

**Comment by kevin49999** [comment]
@leifmetcalf thanks for the note. That's great feedback.

That should be trivial to add I'll make that change and submit a new release soon!

**Comment by kevin49999** [comment]
https://github.com/kevin49999/Go-iOS/pull/19 will merge and submit to apple 🍎

**Comment by kevin49999** [comment]
Fixed in new App Store release [`1.0.3`](https://github.com/kevin49999/Go-iOS/releases/tag/1.0.3)
