### ISSUE TITLE
Problems with putting stones in lost fields

### ISSUE THREAD

**Issue by melangecube** [kevin49999/Go-iOS#20]
Thank you very much for this comforable GO-Game. I really like it an plan to use it in school-lessons (math). 

![Step01](https://github.com/kevin49999/Go-iOS/assets/168718909/1d293bb0-1f11-4898-b783-05c2dd476eb8)
![Step02](https://github.com/kevin49999/Go-iOS/assets/168718909/352f46b8-230c-494c-8258-2ee78bd4b570)

I am  wondering, if the behavior of the app is correct. In first there is a lost field for white. White put one stone into it. Now the white has no more liberties and so it has to disapear. But nothing happend. Maybe it is better to prohibit this like setting in a single eye.

The rule "KO" is not implemented. Is this planed?

**Comment by kevin49999** [comment]
@melangecube thank you for the kind words! And for the detailed message. I will take a look at the "eye" issue you posted screenshots for as well as adding the "KO" rule.

I made this app to learn Go and I'm not an expert, so I really appreciate the feedback! Reading [this](https://www.pandanet.co.jp/English/learning_go/learning_go_7.html) to make sure I understand too. Then I can add a fix and some tests to cover it.

**Comment by kevin49999** [comment]
KO setting added in #22, still keeping open will have a PR to double-check logic around eyes

**Comment by kevin49999** [comment]
https://github.com/kevin49999/Go-iOS/releases/tag/1.1.0 fixed in App Store release `1.1.0`
